# Generated by Django 5.1.6 on 2025-02-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stars',
            name='slug',
            field=models.SlugField(max_length=255, db_index=True, unique=True),
        ),
    ]
