# Generated by Django 5.1.6 on 2025-02-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_stars_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
