# Generated by Django 5.1.6 on 2025-02-20 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0004_category_stars_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stars',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stars.category'),
        ),
    ]
