# Generated by Django 5.1.6 on 2025-03-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0006_alter_stars_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stars',
            name='category',
        ),
    ]
