# Generated by Django 5.1.6 on 2025-03-06 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0007_remove_stars_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stars',
            options={'verbose_name': 'Знаменитости', 'verbose_name_plural': 'Знаменитости'},
        ),
        migrations.AddField(
            model_name='stars',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stars',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
