# Generated by Django 5.1.6 on 2025-03-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0009_alter_category_options_alter_stars_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stars',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stars.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='country',
            field=models.CharField(max_length=20, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
